package main

import (
	"bytes"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestReadModulePathAllowsTrailingComment(t *testing.T) {
	goModPath := filepath.Join(t.TempDir(), "go.mod")
	content := []byte("module goodkind.io/commented // generated by test\n\ngo 1.26.4\n")
	if err := os.WriteFile(goModPath, content, 0o644); err != nil {
		t.Fatalf("writing go.mod: %v", err)
	}

	modulePath, err := readModulePath(goModPath)
	if err != nil {
		t.Fatalf("readModulePath returned error: %v", err)
	}
	if modulePath != "goodkind.io/commented" {
		t.Fatalf("readModulePath = %q, want %q", modulePath, "goodkind.io/commented")
	}
}

func TestBootstrapAssetsMatchCanonicalFiles(t *testing.T) {
	repoRoot := testRepoRoot(t)
	assertFilesEqual(t,
		filepath.Join(repoRoot, "bootstrap.mk"),
		filepath.Join(filepath.Dir(testFilePath(t)), "bootstrap_assets", "bootstrap.mk"),
	)
	assertFilesEqual(t,
		filepath.Join(repoRoot, "templates", "Makefile.tmpl"),
		filepath.Join(filepath.Dir(testFilePath(t)), "bootstrap_assets", "Makefile.tmpl"),
	)
}

func TestReconcileGoModToolsStripsManagedTools(t *testing.T) {
	repoDir := t.TempDir()
	t.Chdir(repoDir)
	goModContent := "module goodkind.io/tooltest\n\ngo 1.26.4\n\n" +
		"tool (\n" +
		"\tgithub.com/golangci/golangci-lint/v2/cmd/golangci-lint\n" +
		"\tgithub.com/fzipp/gocyclo/cmd/gocyclo\n" +
		"\tgolang.org/x/tools/cmd/deadcode\n" +
		"\tgolang.org/x/vuln/cmd/govulncheck\n" +
		"\tgithub.com/bufbuild/buf/cmd/buf\n" +
		")\n"
	writeBootstrapTestFile(t, filepath.Join(repoDir, "go.mod"), goModContent)

	var stdout bytes.Buffer
	if err := reconcileGoModTools(&stdout); err != nil {
		t.Fatalf("reconcileGoModTools returned error: %v", err)
	}

	contents := mustReadFile(t, filepath.Join(repoDir, "go.mod"))
	for _, managed := range goMakefileManagedTools {
		if strings.Contains(contents, managed) {
			t.Fatalf("managed tool directive %q was not removed\ngo.mod:\n%s", managed, contents)
		}
	}
	if !strings.Contains(contents, "github.com/bufbuild/buf/cmd/buf") {
		t.Fatalf("project-specific tool directive was removed\ngo.mod:\n%s", contents)
	}

	// Re-running is a no-op now that no managed tool directive remains.
	before := contents
	var secondStdout bytes.Buffer
	if err := reconcileGoModTools(&secondStdout); err != nil {
		t.Fatalf("second reconcileGoModTools returned error: %v", err)
	}
	if after := mustReadFile(t, filepath.Join(repoDir, "go.mod")); after != before {
		t.Fatalf("second run changed go.mod\nbefore:\n%s\nafter:\n%s", before, after)
	}
}

func TestBootstrapScenarios(t *testing.T) {
	repoRoot := testRepoRoot(t)

	t.Run("new binary repo", func(t *testing.T) {
		repoDir := filepath.Join(t.TempDir(), "binary")
		mustMkdirAll(t, repoDir)
		t.Chdir(repoDir)

		runBootstrapForTest(t, bootstrapOptions{
			modulePath:  "goodkind.io/bootstrap-probe",
			forceBinary: true,
			yes:         true,
		})

		assertFileExists(t, filepath.Join(repoDir, "go.mod"))
		assertFileExists(t, filepath.Join(repoDir, "Makefile"))
		assertFileExists(t, filepath.Join(repoDir, "bootstrap.mk"))
		assertFileExists(t, filepath.Join(repoDir, ".gitignore"))
		ciWorkflow := filepath.Join(repoDir, ".github", "workflows", "ci.yml")
		assertFileExists(t, ciWorkflow)
		assertFileContains(t, ciWorkflow, "branches: ['**']")
		assertFileContains(t, ciWorkflow, "agoodkind/go-makefile/.github/workflows/_ci.yml@main")
		releaseWorkflow := filepath.Join(repoDir, ".github", "workflows", "release.yml")
		assertFileExists(t, releaseWorkflow)
		assertFileContains(t, releaseWorkflow, "agoodkind/go-makefile/.github/workflows/_release.yml@main")
		assertFileContains(t, releaseWorkflow, "id-token: write")
		assertFileContains(t, releaseWorkflow, "attestations: write")
		assertFileContains(t, releaseWorkflow, "      binary: bootstrap-probe")
		assertBootstrapTrackedFilesAbsent(t, repoDir)
		assertFileContains(t, filepath.Join(repoDir, "Makefile"), "BINARY := bootstrap-probe")
		assertFileContains(t, filepath.Join(repoDir, "Makefile"), "GO_MK_MODULES := go-build.mk go-release.mk")
		assertFileContains(t, filepath.Join(repoDir, "bootstrap.mk"), "GO_MK_BOOTSTRAP_FETCHED := 1")
		assertFileContains(t, filepath.Join(repoDir, ".gitignore"), ".make/")
		assertGitignoreContainsBootstrapEntries(t, repoDir, configuredBootstrapTrackedFiles())
		runMakeHelp(t, repoDir, repoRoot)
	})

	t.Run("new library repo", func(t *testing.T) {
		repoDir := filepath.Join(t.TempDir(), "library")
		mustMkdirAll(t, repoDir)
		t.Chdir(repoDir)

		runBootstrapForTest(t, bootstrapOptions{
			modulePath:   "goodkind.io/bootstrap-library",
			forceLibrary: true,
			yes:          true,
		})

		assertFileContains(t, filepath.Join(repoDir, "Makefile"), "LIBRARY := 1")
		assertFileContains(t, filepath.Join(repoDir, "Makefile"), "GO_MK_MODULES := go-build.mk")
		assertFileExists(t, filepath.Join(repoDir, "bootstrap.mk"))
		assertBootstrapTrackedFilesAbsent(t, repoDir)
		assertGitignoreContainsBootstrapEntries(t, repoDir, configuredBootstrapTrackedFiles())
	})

	t.Run("custom Makefile is preserved", func(t *testing.T) {
		repoDir := filepath.Join(t.TempDir(), "custom")
		mustMkdirAll(t, repoDir)
		writeBootstrapTestGoMod(t, repoDir, "goodkind.io/custom")
		writeBootstrapTestFile(t, filepath.Join(repoDir, "Makefile"), "custom:\n\t@echo custom\n")
		originalMakefile := mustReadFile(t, filepath.Join(repoDir, "Makefile"))
		t.Chdir(repoDir)

		runBootstrapForTest(t, bootstrapOptions{yes: true})

		if currentMakefile := mustReadFile(t, filepath.Join(repoDir, "Makefile")); currentMakefile != originalMakefile {
			t.Fatalf("custom Makefile changed\nbefore:\n%s\nafter:\n%s", originalMakefile, currentMakefile)
		}
		assertFileExists(t, filepath.Join(repoDir, "bootstrap.mk"))
		assertFileContains(t, filepath.Join(repoDir, ".gitignore"), ".make/")
		assertBootstrapTrackedFilesAbsent(t, repoDir)
		assertGitignoreContainsBootstrapEntries(t, repoDir, configuredBootstrapTrackedFiles())
	})

	t.Run("generated rerun is stable", func(t *testing.T) {
		repoDir := filepath.Join(t.TempDir(), "rerun")
		mustMkdirAll(t, repoDir)
		t.Chdir(repoDir)

		runBootstrapForTest(t, bootstrapOptions{
			modulePath:  "goodkind.io/rerun",
			forceBinary: true,
			yes:         true,
		})

		ciWorkflow := filepath.Join(repoDir, ".github", "workflows", "ci.yml")
		releaseWorkflow := filepath.Join(repoDir, ".github", "workflows", "release.yml")
		beforeMakefile := mustReadFile(t, filepath.Join(repoDir, "Makefile"))
		beforeBootstrap := mustReadFile(t, filepath.Join(repoDir, "bootstrap.mk"))
		beforeGitignore := mustReadFile(t, filepath.Join(repoDir, ".gitignore"))
		beforeCIWorkflow := mustReadFile(t, ciWorkflow)
		beforeReleaseWorkflow := mustReadFile(t, releaseWorkflow)

		runBootstrapForTest(t, bootstrapOptions{
			modulePath:  "goodkind.io/rerun",
			forceBinary: true,
			yes:         true,
		})

		assertFileText(t, filepath.Join(repoDir, "Makefile"), beforeMakefile)
		assertFileText(t, filepath.Join(repoDir, "bootstrap.mk"), beforeBootstrap)
		assertFileText(t, filepath.Join(repoDir, ".gitignore"), beforeGitignore)
		assertFileText(t, ciWorkflow, beforeCIWorkflow)
		assertFileText(t, releaseWorkflow, beforeReleaseWorkflow)
	})

	t.Run("custom ci.yml is preserved", func(t *testing.T) {
		repoDir := filepath.Join(t.TempDir(), "custom-ci")
		mustMkdirAll(t, repoDir)
		writeBootstrapTestGoMod(t, repoDir, "goodkind.io/custom-ci")
		ciWorkflow := filepath.Join(repoDir, ".github", "workflows", "ci.yml")
		mustMkdirAll(t, filepath.Dir(ciWorkflow))
		customWorkflow := "name: CI\non:\n  push:\n    branches: [main]\njobs:\n  custom:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo custom\n"
		writeBootstrapTestFile(t, ciWorkflow, customWorkflow)
		t.Chdir(repoDir)

		runBootstrapForTest(t, bootstrapOptions{yes: true})

		assertFileText(t, ciWorkflow, customWorkflow)
	})

	t.Run("generated Makefile is repaired", func(t *testing.T) {
		repoDir := filepath.Join(t.TempDir(), "repair")
		mustMkdirAll(t, repoDir)
		t.Chdir(repoDir)

		runBootstrapForTest(t, bootstrapOptions{
			modulePath:  "goodkind.io/repair",
			forceBinary: true,
			yes:         true,
		})

		makefilePath := filepath.Join(repoDir, "Makefile")
		withoutInclude := strings.ReplaceAll(mustReadFile(t, makefilePath), "include bootstrap.mk\n", "")
		writeBootstrapTestFile(t, makefilePath, withoutInclude)

		runBootstrapForTest(t, bootstrapOptions{
			modulePath:  "goodkind.io/repair",
			forceBinary: true,
			yes:         true,
		})

		assertFileContains(t, makefilePath, "include bootstrap.mk")
	})

	t.Run("baseline files are unignored", func(t *testing.T) {
		repoDir := filepath.Join(t.TempDir(), "unignored")
		mustMkdirAll(t, repoDir)
		initGitRepo(t, repoDir)
		t.Setenv("GOLANGCI_LINT_BASELINE", "baselines/golangci.txt")
		writeBootstrapTestFile(t, filepath.Join(repoDir, ".gitignore"), "*.txt\nbaselines/\n.*\n")
		t.Chdir(repoDir)

		runBootstrapForTest(t, bootstrapOptions{
			modulePath:   "goodkind.io/unignored",
			forceLibrary: true,
			yes:          true,
		})

		assertGitignoreContainsBootstrapEntries(t, repoDir, configuredBootstrapTrackedFiles())
		for _, trackedFile := range configuredBootstrapTrackedFiles() {
			assertPathNotGitIgnored(t, repoDir, trackedFile)
		}
	})
}

func TestReconcileReleaseWorkflow(t *testing.T) {
	t.Run("scaffolds when absent", func(t *testing.T) {
		repoDir := t.TempDir()
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileReleaseWorkflow("", &stdout); err != nil {
			t.Fatalf("reconcileReleaseWorkflow returned error: %v", err)
		}

		releaseWorkflow := filepath.Join(repoDir, ".github", "workflows", "release.yml")
		assertFileExists(t, releaseWorkflow)
		assertFileContains(t, releaseWorkflow, "agoodkind/go-makefile/.github/workflows/_release.yml@main")
		assertFileContains(t, releaseWorkflow, "contents: write")
		assertFileContains(t, releaseWorkflow, "id-token: write")
		assertFileContains(t, releaseWorkflow, "attestations: write")
		assertFileContains(t, releaseWorkflow, "secrets: inherit")

		before := mustReadFile(t, releaseWorkflow)
		var secondStdout bytes.Buffer
		if err := reconcileReleaseWorkflow("", &secondStdout); err != nil {
			t.Fatalf("second reconcileReleaseWorkflow returned error: %v", err)
		}
		assertFileText(t, releaseWorkflow, before)
	})

	t.Run("scaffolds binary input when absent", func(t *testing.T) {
		repoDir := t.TempDir()
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileReleaseWorkflow("agent-gate", &stdout); err != nil {
			t.Fatalf("reconcileReleaseWorkflow returned error: %v", err)
		}

		releaseWorkflow := filepath.Join(repoDir, ".github", "workflows", "release.yml")
		assertFileContains(t, releaseWorkflow, "    with:\n      binary: agent-gate\n")

		before := mustReadFile(t, releaseWorkflow)
		var secondStdout bytes.Buffer
		if err := reconcileReleaseWorkflow("agent-gate", &secondStdout); err != nil {
			t.Fatalf("second reconcileReleaseWorkflow returned error: %v", err)
		}
		assertFileText(t, releaseWorkflow, before)
	})

	t.Run("repairs missing permissions in place", func(t *testing.T) {
		repoDir := t.TempDir()
		releaseWorkflow := filepath.Join(repoDir, ".github", "workflows", "release.yml")
		mustMkdirAll(t, filepath.Dir(releaseWorkflow))
		drifted := "name: Release\n\n" +
			"on:\n" +
			"  push:\n" +
			"    tags: ['v*']\n\n" +
			"jobs:\n" +
			"  release:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_release.yml@main\n" +
			"    permissions:\n" +
			"      contents: write\n" +
			"    with:\n" +
			"      cgo: true\n" +
			"    secrets: inherit\n"
		writeBootstrapTestFile(t, releaseWorkflow, drifted)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileReleaseWorkflow("", &stdout); err != nil {
			t.Fatalf("reconcileReleaseWorkflow returned error: %v", err)
		}

		repaired := mustReadFile(t, releaseWorkflow)
		expected := "name: Release\n\n" +
			"on:\n" +
			"  push:\n" +
			"    tags: ['v*']\n\n" +
			"jobs:\n" +
			"  release:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_release.yml@main\n" +
			"    permissions:\n" +
			"      contents: write\n" +
			"      id-token: write\n" +
			"      attestations: write\n" +
			"    with:\n" +
			"      cgo: true\n" +
			"    secrets: inherit\n"
		if repaired != expected {
			t.Fatalf("repaired release.yml mismatch\nwant:\n%s\ngot:\n%s", expected, repaired)
		}

		// Idempotent: a second run leaves the repaired file byte-identical.
		var secondStdout bytes.Buffer
		if err := reconcileReleaseWorkflow("", &secondStdout); err != nil {
			t.Fatalf("second reconcileReleaseWorkflow returned error: %v", err)
		}
		assertFileText(t, releaseWorkflow, expected)
	})

	t.Run("repairs missing binary input in place", func(t *testing.T) {
		repoDir := t.TempDir()
		releaseWorkflow := filepath.Join(repoDir, ".github", "workflows", "release.yml")
		mustMkdirAll(t, filepath.Dir(releaseWorkflow))
		drifted := "name: Release\n\n" +
			"jobs:\n" +
			"  release:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_release.yml@main\n" +
			"    permissions:\n" +
			"      contents: write\n" +
			"      id-token: write\n" +
			"      attestations: write\n" +
			"    with:\n" +
			"      cgo: true\n" +
			"    secrets: inherit\n"
		writeBootstrapTestFile(t, releaseWorkflow, drifted)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileReleaseWorkflow("agent-gate", &stdout); err != nil {
			t.Fatalf("reconcileReleaseWorkflow returned error: %v", err)
		}

		expected := "name: Release\n\n" +
			"jobs:\n" +
			"  release:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_release.yml@main\n" +
			"    permissions:\n" +
			"      contents: write\n" +
			"      id-token: write\n" +
			"      attestations: write\n" +
			"    with:\n" +
			"      cgo: true\n" +
			"      binary: agent-gate\n" +
			"    secrets: inherit\n"
		if repaired := mustReadFile(t, releaseWorkflow); repaired != expected {
			t.Fatalf("release.yml mismatch\nwant:\n%s\ngot:\n%s", expected, repaired)
		}

		var secondStdout bytes.Buffer
		if err := reconcileReleaseWorkflow("agent-gate", &secondStdout); err != nil {
			t.Fatalf("second reconcileReleaseWorkflow returned error: %v", err)
		}
		assertFileText(t, releaseWorkflow, expected)
	})

	t.Run("adds permissions block when job has none", func(t *testing.T) {
		repoDir := t.TempDir()
		releaseWorkflow := filepath.Join(repoDir, ".github", "workflows", "release.yml")
		mustMkdirAll(t, filepath.Dir(releaseWorkflow))
		withoutPermissions := "name: Release\n\n" +
			"jobs:\n" +
			"  release:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_release.yml@main\n" +
			"    secrets: inherit\n"
		writeBootstrapTestFile(t, releaseWorkflow, withoutPermissions)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileReleaseWorkflow("", &stdout); err != nil {
			t.Fatalf("reconcileReleaseWorkflow returned error: %v", err)
		}

		expected := "name: Release\n\n" +
			"jobs:\n" +
			"  release:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_release.yml@main\n" +
			"    permissions:\n" +
			"      contents: write\n" +
			"      id-token: write\n" +
			"      attestations: write\n" +
			"    secrets: inherit\n"
		if repaired := mustReadFile(t, releaseWorkflow); repaired != expected {
			t.Fatalf("release.yml mismatch\nwant:\n%s\ngot:\n%s", expected, repaired)
		}
	})

	t.Run("custom release.yml is preserved", func(t *testing.T) {
		repoDir := t.TempDir()
		releaseWorkflow := filepath.Join(repoDir, ".github", "workflows", "release.yml")
		mustMkdirAll(t, filepath.Dir(releaseWorkflow))
		custom := "name: Release\non:\n  push:\n    tags: ['v*']\njobs:\n  release:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo release\n"
		writeBootstrapTestFile(t, releaseWorkflow, custom)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileReleaseWorkflow("", &stdout); err != nil {
			t.Fatalf("reconcileReleaseWorkflow returned error: %v", err)
		}

		assertFileText(t, releaseWorkflow, custom)
	})

	t.Run("scalar write-all permissions is left untouched", func(t *testing.T) {
		repoDir := t.TempDir()
		releaseWorkflow := filepath.Join(repoDir, ".github", "workflows", "release.yml")
		mustMkdirAll(t, filepath.Dir(releaseWorkflow))
		scalar := "name: Release\n\n" +
			"jobs:\n" +
			"  release:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_release.yml@main\n" +
			"    permissions: write-all\n" +
			"    secrets: inherit\n"
		writeBootstrapTestFile(t, releaseWorkflow, scalar)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileReleaseWorkflow("", &stdout); err != nil {
			t.Fatalf("reconcileReleaseWorkflow returned error: %v", err)
		}

		// A second permissions key would be invalid YAML, so the caller stays byte-identical.
		assertFileText(t, releaseWorkflow, scalar)
		if strings.Count(mustReadFile(t, releaseWorkflow), "permissions") != 1 {
			t.Fatalf("scalar caller gained a duplicate permissions key\ncontents:\n%s", mustReadFile(t, releaseWorkflow))
		}

		var secondStdout bytes.Buffer
		if err := reconcileReleaseWorkflow("", &secondStdout); err != nil {
			t.Fatalf("second reconcileReleaseWorkflow returned error: %v", err)
		}
		assertFileText(t, releaseWorkflow, scalar)
	})

	t.Run("inline-map permissions is left untouched", func(t *testing.T) {
		repoDir := t.TempDir()
		releaseWorkflow := filepath.Join(repoDir, ".github", "workflows", "release.yml")
		mustMkdirAll(t, filepath.Dir(releaseWorkflow))
		inline := "name: Release\n\n" +
			"jobs:\n" +
			"  release:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_release.yml@main\n" +
			"    permissions: { contents: write }\n" +
			"    secrets: inherit\n"
		writeBootstrapTestFile(t, releaseWorkflow, inline)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileReleaseWorkflow("", &stdout); err != nil {
			t.Fatalf("reconcileReleaseWorkflow returned error: %v", err)
		}

		assertFileText(t, releaseWorkflow, inline)
		if strings.Count(mustReadFile(t, releaseWorkflow), "permissions") != 1 {
			t.Fatalf("inline-map caller gained a duplicate permissions key\ncontents:\n%s", mustReadFile(t, releaseWorkflow))
		}

		var secondStdout bytes.Buffer
		if err := reconcileReleaseWorkflow("", &secondStdout); err != nil {
			t.Fatalf("second reconcileReleaseWorkflow returned error: %v", err)
		}
		assertFileText(t, releaseWorkflow, inline)
	})

	t.Run("wrong-value block permission is upgraded", func(t *testing.T) {
		repoDir := t.TempDir()
		releaseWorkflow := filepath.Join(repoDir, ".github", "workflows", "release.yml")
		mustMkdirAll(t, filepath.Dir(releaseWorkflow))
		wrongValue := "name: Release\n\n" +
			"jobs:\n" +
			"  release:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_release.yml@main\n" +
			"    permissions:\n" +
			"      contents: read\n" +
			"    secrets: inherit\n"
		writeBootstrapTestFile(t, releaseWorkflow, wrongValue)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileReleaseWorkflow("", &stdout); err != nil {
			t.Fatalf("reconcileReleaseWorkflow returned error: %v", err)
		}

		expected := "name: Release\n\n" +
			"jobs:\n" +
			"  release:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_release.yml@main\n" +
			"    permissions:\n" +
			"      contents: write\n" +
			"      id-token: write\n" +
			"      attestations: write\n" +
			"    secrets: inherit\n"
		if repaired := mustReadFile(t, releaseWorkflow); repaired != expected {
			t.Fatalf("release.yml mismatch\nwant:\n%s\ngot:\n%s", expected, repaired)
		}

		// Idempotent: the corrected caller stays byte-identical on a second run.
		var secondStdout bytes.Buffer
		if err := reconcileReleaseWorkflow("", &secondStdout); err != nil {
			t.Fatalf("second reconcileReleaseWorkflow returned error: %v", err)
		}
		assertFileText(t, releaseWorkflow, expected)
	})
}

func TestReconcileCIWorkflow(t *testing.T) {
	t.Run("scaffolds when absent with signing grants", func(t *testing.T) {
		repoDir := t.TempDir()
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileCIWorkflow(&stdout); err != nil {
			t.Fatalf("reconcileCIWorkflow returned error: %v", err)
		}

		ciWorkflow := filepath.Join(repoDir, ".github", "workflows", "ci.yml")
		assertFileExists(t, ciWorkflow)
		assertFileContains(t, ciWorkflow, "agoodkind/go-makefile/.github/workflows/_ci.yml@main")
		assertFileContains(t, ciWorkflow, "attestations: write")
		assertFileContains(t, ciWorkflow, "secrets: inherit")

		before := mustReadFile(t, ciWorkflow)
		var secondStdout bytes.Buffer
		if err := reconcileCIWorkflow(&secondStdout); err != nil {
			t.Fatalf("second reconcileCIWorkflow returned error: %v", err)
		}
		assertFileText(t, ciWorkflow, before)
	})

	t.Run("repairs missing grants in place", func(t *testing.T) {
		repoDir := t.TempDir()
		ciWorkflow := filepath.Join(repoDir, ".github", "workflows", "ci.yml")
		mustMkdirAll(t, filepath.Dir(ciWorkflow))
		drifted := "name: CI\n\n" +
			"on:\n" +
			"  push:\n" +
			"    branches: ['**']\n\n" +
			"jobs:\n" +
			"  go:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_ci.yml@main\n" +
			"    permissions:\n" +
			"      contents: read\n" +
			"      id-token: write\n" +
			"    with:\n" +
			"      apt_packages: libpcre2-dev\n"
		writeBootstrapTestFile(t, ciWorkflow, drifted)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileCIWorkflow(&stdout); err != nil {
			t.Fatalf("reconcileCIWorkflow returned error: %v", err)
		}

		// attestations is appended to the permissions block; secrets: inherit is
		// inserted right after the uses line. contents: read is never rewritten.
		expected := "name: CI\n\n" +
			"on:\n" +
			"  push:\n" +
			"    branches: ['**']\n\n" +
			"jobs:\n" +
			"  go:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_ci.yml@main\n" +
			"    secrets: inherit\n" +
			"    permissions:\n" +
			"      contents: read\n" +
			"      id-token: write\n" +
			"      attestations: write\n" +
			"    with:\n" +
			"      apt_packages: libpcre2-dev\n"
		if repaired := mustReadFile(t, ciWorkflow); repaired != expected {
			t.Fatalf("repaired ci.yml mismatch\nwant:\n%s\ngot:\n%s", expected, repaired)
		}

		// Idempotent: a second run leaves the repaired file byte-identical.
		var secondStdout bytes.Buffer
		if err := reconcileCIWorkflow(&secondStdout); err != nil {
			t.Fatalf("second reconcileCIWorkflow returned error: %v", err)
		}
		assertFileText(t, ciWorkflow, expected)
	})

	t.Run("adds permissions block and secrets when job has none", func(t *testing.T) {
		repoDir := t.TempDir()
		ciWorkflow := filepath.Join(repoDir, ".github", "workflows", "ci.yml")
		mustMkdirAll(t, filepath.Dir(ciWorkflow))
		withoutGrants := "name: CI\n\n" +
			"jobs:\n" +
			"  go:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_ci.yml@main\n"
		writeBootstrapTestFile(t, ciWorkflow, withoutGrants)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileCIWorkflow(&stdout); err != nil {
			t.Fatalf("reconcileCIWorkflow returned error: %v", err)
		}

		expected := "name: CI\n\n" +
			"jobs:\n" +
			"  go:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_ci.yml@main\n" +
			"    secrets: inherit\n" +
			"    permissions:\n" +
			"      contents: read\n" +
			"      id-token: write\n" +
			"      attestations: write\n"
		if repaired := mustReadFile(t, ciWorkflow); repaired != expected {
			t.Fatalf("ci.yml mismatch\nwant:\n%s\ngot:\n%s", expected, repaired)
		}
	})

	t.Run("block missing contents gets contents read added", func(t *testing.T) {
		repoDir := t.TempDir()
		ciWorkflow := filepath.Join(repoDir, ".github", "workflows", "ci.yml")
		mustMkdirAll(t, filepath.Dir(ciWorkflow))
		missingContents := "name: CI\n\n" +
			"jobs:\n" +
			"  go:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_ci.yml@main\n" +
			"    permissions:\n" +
			"      id-token: write\n" +
			"      attestations: write\n" +
			"    secrets: inherit\n"
		writeBootstrapTestFile(t, ciWorkflow, missingContents)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileCIWorkflow(&stdout); err != nil {
			t.Fatalf("reconcileCIWorkflow returned error: %v", err)
		}

		// A permissions block that omits contents would leave contents at none
		// and break checkout, so contents: read is appended.
		expected := "name: CI\n\n" +
			"jobs:\n" +
			"  go:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_ci.yml@main\n" +
			"    permissions:\n" +
			"      id-token: write\n" +
			"      attestations: write\n" +
			"      contents: read\n" +
			"    secrets: inherit\n"
		if repaired := mustReadFile(t, ciWorkflow); repaired != expected {
			t.Fatalf("ci.yml mismatch\nwant:\n%s\ngot:\n%s", expected, repaired)
		}
	})

	t.Run("already-current caller is untouched", func(t *testing.T) {
		repoDir := t.TempDir()
		ciWorkflow := filepath.Join(repoDir, ".github", "workflows", "ci.yml")
		mustMkdirAll(t, filepath.Dir(ciWorkflow))
		current := "name: CI\n\n" +
			"jobs:\n" +
			"  go:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_ci.yml@main\n" +
			"    permissions:\n" +
			"      contents: read\n" +
			"      id-token: write\n" +
			"      attestations: write\n" +
			"    secrets: inherit\n" +
			"    with:\n" +
			"      apt_packages: libpcre2-dev\n"
		writeBootstrapTestFile(t, ciWorkflow, current)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileCIWorkflow(&stdout); err != nil {
			t.Fatalf("reconcileCIWorkflow returned error: %v", err)
		}
		assertFileText(t, ciWorkflow, current)
	})

	t.Run("comment under uses stays attached", func(t *testing.T) {
		repoDir := t.TempDir()
		ciWorkflow := filepath.Join(repoDir, ".github", "workflows", "ci.yml")
		mustMkdirAll(t, filepath.Dir(ciWorkflow))
		commented := "name: CI\n\n" +
			"jobs:\n" +
			"  go:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_ci.yml@main\n" +
			"    # documents the reusable CI caller\n" +
			"    permissions:\n" +
			"      contents: read\n" +
			"      id-token: write\n" +
			"      attestations: write\n"
		writeBootstrapTestFile(t, ciWorkflow, commented)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileCIWorkflow(&stdout); err != nil {
			t.Fatalf("reconcileCIWorkflow returned error: %v", err)
		}

		// secrets: inherit lands after the comment block, keeping the comment
		// attached to the uses line it documents.
		expected := "name: CI\n\n" +
			"jobs:\n" +
			"  go:\n" +
			"    uses: agoodkind/go-makefile/.github/workflows/_ci.yml@main\n" +
			"    # documents the reusable CI caller\n" +
			"    secrets: inherit\n" +
			"    permissions:\n" +
			"      contents: read\n" +
			"      id-token: write\n" +
			"      attestations: write\n"
		if repaired := mustReadFile(t, ciWorkflow); repaired != expected {
			t.Fatalf("ci.yml mismatch\nwant:\n%s\ngot:\n%s", expected, repaired)
		}
	})

	t.Run("custom ci.yml is preserved", func(t *testing.T) {
		repoDir := t.TempDir()
		ciWorkflow := filepath.Join(repoDir, ".github", "workflows", "ci.yml")
		mustMkdirAll(t, filepath.Dir(ciWorkflow))
		custom := "name: CI\non:\n  push:\n    branches: ['**']\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo test\n"
		writeBootstrapTestFile(t, ciWorkflow, custom)
		t.Chdir(repoDir)

		var stdout bytes.Buffer
		if err := reconcileCIWorkflow(&stdout); err != nil {
			t.Fatalf("reconcileCIWorkflow returned error: %v", err)
		}
		assertFileText(t, ciWorkflow, custom)
	})
}

func runBootstrapForTest(t *testing.T, options bootstrapOptions) {
	t.Helper()
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	options.stdout = &stdout
	options.stderr = &stderr
	if err := runBootstrap(options); err != nil {
		t.Fatalf("runBootstrap returned error: %v\nstdout:\n%s\nstderr:\n%s", err, stdout.String(), stderr.String())
	}
}

func runMakeHelp(t *testing.T, repoDir string, repoRoot string) {
	t.Helper()
	command := exec.Command("make", "help")
	command.Dir = repoDir
	command.Env = append(os.Environ(), "GO_MK_DEV_DIR="+repoRoot)
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("make help failed: %v\noutput:\n%s", err, string(output))
	}
}

func initGitRepo(t *testing.T, repoDir string) {
	t.Helper()
	command := exec.Command("git", "init", "-q")
	command.Dir = repoDir
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("git init failed: %v\noutput:\n%s", err, string(output))
	}
}

func assertPathNotGitIgnored(t *testing.T, repoDir string, filePath string) {
	t.Helper()
	command := exec.Command("git", "check-ignore", "--quiet", filePath)
	command.Dir = repoDir
	err := command.Run()
	if err == nil {
		t.Fatalf("%s is still gitignored", filePath)
	}
	var exitError *exec.ExitError
	if !errors.As(err, &exitError) {
		t.Fatalf("git check-ignore %s: %v", filePath, err)
	}
	if exitError.ExitCode() != 1 {
		output, outputErr := exec.Command("git", "check-ignore", "-v", filePath).CombinedOutput()
		if outputErr != nil {
			t.Fatalf("git check-ignore -v %s: %v", filePath, outputErr)
		}
		t.Fatalf("git check-ignore %s returned exit code %d\noutput:\n%s", filePath, exitError.ExitCode(), string(output))
	}
}

func assertFileExists(t *testing.T, filePath string) {
	t.Helper()
	info, err := os.Stat(filePath)
	if err != nil {
		t.Fatalf("stat %s: %v", filePath, err)
	}
	if info.IsDir() {
		t.Fatalf("%s is a directory, want file", filePath)
	}
}

func assertFileContains(t *testing.T, filePath string, expectedText string) {
	t.Helper()
	contents := mustReadFile(t, filePath)
	if !strings.Contains(contents, expectedText) {
		t.Fatalf("%s does not contain %q\ncontents:\n%s", filePath, expectedText, contents)
	}
}

func assertBootstrapTrackedFilesAbsent(t *testing.T, repoDir string) {
	t.Helper()
	for _, trackedFile := range configuredBootstrapTrackedFiles() {
		filePath := filepath.Join(repoDir, trackedFile)
		if _, err := os.Stat(filePath); !os.IsNotExist(err) {
			t.Fatalf("stat %s = %v, want not exist", filePath, err)
		}
	}
}

func assertGitignoreContainsBootstrapEntries(t *testing.T, repoDir string, baselineFiles []string) {
	t.Helper()
	gitignorePath := filepath.Join(repoDir, ".gitignore")
	for _, entry := range bootstrapGitignoreEntries(baselineFiles) {
		assertFileContains(t, gitignorePath, entry)
	}
}

func assertFileText(t *testing.T, filePath string, expectedText string) {
	t.Helper()
	if actualText := mustReadFile(t, filePath); actualText != expectedText {
		t.Fatalf("%s changed unexpectedly\nwant:\n%s\ngot:\n%s", filePath, expectedText, actualText)
	}
}

func assertFilesEqual(t *testing.T, expectedPath string, actualPath string) {
	t.Helper()
	expectedContents, err := os.ReadFile(expectedPath)
	if err != nil {
		t.Fatalf("read %s: %v", expectedPath, err)
	}
	actualContents, err := os.ReadFile(actualPath)
	if err != nil {
		t.Fatalf("read %s: %v", actualPath, err)
	}
	if !bytes.Equal(expectedContents, actualContents) {
		t.Fatalf("files differ: %s %s", expectedPath, actualPath)
	}
}

func mustReadFile(t *testing.T, filePath string) string {
	t.Helper()
	contents, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatalf("read %s: %v", filePath, err)
	}
	return string(contents)
}

func writeBootstrapTestFile(t *testing.T, filePath string, contents string) {
	t.Helper()
	if err := os.WriteFile(filePath, []byte(contents), 0o644); err != nil {
		t.Fatalf("write %s: %v", filePath, err)
	}
}

func writeBootstrapTestGoMod(t *testing.T, repoDir string, modulePath string) {
	t.Helper()
	writeBootstrapTestFile(t, filepath.Join(repoDir, "go.mod"), "module "+modulePath+"\n\ngo 1.26.4\n")
}

func mustMkdirAll(t *testing.T, directoryPath string) {
	t.Helper()
	if err := os.MkdirAll(directoryPath, 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", directoryPath, err)
	}
}

func testRepoRoot(t *testing.T) string {
	t.Helper()
	return filepath.Clean(filepath.Join(filepath.Dir(testFilePath(t)), "..", ".."))
}

func testFilePath(t *testing.T) string {
	t.Helper()
	_, filePath, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed")
	}
	return filePath
}
