package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestReadModulePathAllowsTrailingComment(t *testing.T) {
	t.Parallel()

	goModPath := filepath.Join(t.TempDir(), "go.mod")
	content := []byte("module goodkind.io/commented // generated by test\n\ngo 1.26.4\n")
	if err := os.WriteFile(goModPath, content, 0o644); err != nil {
		t.Fatalf("writing go.mod: %v", err)
	}

	modulePath, err := readModulePath(goModPath)
	if err != nil {
		t.Fatalf("readModulePath returned error: %v", err)
	}
	if modulePath != "goodkind.io/commented" {
		t.Fatalf("readModulePath = %q, want %q", modulePath, "goodkind.io/commented")
	}
}
