name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  go:
    uses: ./.github/workflows/_ci.yml
    permissions:
      contents: read
      id-token: write
