name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  go:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/_ci.yml
    permissions:
      contents: read
      id-token: write

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
    secrets: inherit
