name: CI

on:
  push:
    branches: ['**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  go:
    uses: ./.github/workflows/_ci.yml
    permissions:
      contents: read
      id-token: write
